Starts a container in the deployment phase, cleans up on sandbox end
nasa-gcn/architect-plugin-dynamodb-local pull request #1
Opened 2024-12-19 15:14 UTC by dakota002

Mostly adapted from https://github.com/nasa-gcn/architect-plugin-search

Important notes:

This needs to start in the deploy phase, so that the docker container gets started before the @tables pragma stuff starts trying to populate tables

Mostly working at the moment, just trying to resolve a "socket hang up" issue

2025-01-17 17:31 UTC, lpsinger requested changes

2025-01-17 17:31 UTC, lpsinger commented on runDocker.ts
> +      Binds: [`${dataDir}:/home/dynamodblocal/data`],
Remove bind mount. There's no need to persist the data to the host filesystem.

2025-01-17 17:31 UTC, lpsinger commented on index.ts
> +    local = await launch()
Why is this in `deploy.services`, not `sandbox.start`?

2025-01-23 21:53 UTC, dakota002 commented on runDocker.ts
> +      Binds: [`${dataDir}:/home/dynamodblocal/data`],
I realized i could just use the run function from docker, I have updated it in the latest commit. I still need to clean it up, but it should be behaving as expected.

2025-01-27 21:25 UTC, closed without merging